# Generated by Django 5.0.4 on 2024-04-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippaste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
